import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { NavBar } from "../components/NavBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doblefilo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <div className={styles.main}>
          <h1 className={styles.title}>
            Hi! I'm <span className={styles.name}>Marc Rodríguez</span>
          </h1>
          <h3 className={styles.subtitle}>
            Backend Developer Trainee at{" "}
            <span className={styles.job}>Genially</span>
          </h3>
        </div>
      </main>
    </div>
  );
}
